# Generated by Django 3.0.5 on 2020-07-24 15:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200724_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllUserProfile',
            new_name='CustomerProfile',
        ),
    ]
