# Generated by Django 3.0.5 on 2020-07-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
