# Generated by Django 3.0.5 on 2020-08-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200805_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='core.Variation'),
        ),
    ]
